### ISSUE TITLE
pvr.stalker not loading stalker portal

### ISSUE THREAD

**Issue by cchalk** [kodi-pvr/pvr.stalker#35]
Hi,

I upgraded to the latest Kodi release 16.0 Alpha 4 and compiled this addon and it wouldn't connect to any of the stalker portals that I use.

[pvr.stalker.master.error.kodi16.txt](https://github.com/kodi-pvr/pvr.stalker/files/34416/pvr.stalker.master.error.kodi16.txt)

After I reverted the "dropped http redirect. protocol options for http(s) stream urls only" commit face067dd9a833ac0aaba6e2e5dd9f414f4c the addon would connect to the portals I use again.

Thanks.

**Comment by kenji123** [comment]
That was an intended change done in that commit. Before the add-on would try to follow redirects by parsing the html in the initial http response. This always felt 'wrong' to me since there are many ways a redirect can occur in html, and it's just not practical to do so in the case of this add-on. Also, only the first redirect was considered. I think it's best that the full url be entered by the user in the settings dialog.

So, for example if you used to enter 'server.example.com' you may now need to enter 'server.example.com/stalker_portal/c/'.

The simplest way to get the final/full url of your portal is to enter it into a web browser and copy the new address from the address bar.

**Comment by cchalk** [comment]
Hi,

Thanks for the explanation.

I have been using the add-on for a while now and it's working great. Thanks.
